package com.aman.notesapp

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.aman.notesapp.presentation.ui.FavList

@Entity(tableName="notes_table")
//TODO Create 3 columns in table
class Note(@ColumnInfo(name="title") val title:String,@ColumnInfo(name="body")  val body:String,@ColumnInfo(name="fav")  val fav:Boolean ) {
    @PrimaryKey(autoGenerate = true) var id=0
    //ID is autogenerated
}